### ISSUE TITLE
How do you do local Umbrel Development with CORS disabled

### ISSUE THREAD

**Issue by timjrobinson** [getumbrel/umbrel-manager#120]
I recently updated my local dev of umbrel-manager and it included #118. I've been developing by running the dashboard locally on port 8080 (launching with `npm run serve`) and the manager on port 8081 (launching with `yarn start`) . Without CORS headers they can't talk to each other in this way. 

So you must do development in a different way. Is there any guides or docs on how to develop umbrel locally correctly?

**Comment by lukechilds** [comment]
Yeah we use umbrel-dev: https://github.com/getumbrel/umbrel-dev
