### ISSUE TITLE
Change password fails on RPi 3

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-manager#30]
From: https://github.com/getumbrel/umbrel-os/issues/64#issuecomment-666545700

```
manager | ::ffff:10.11.0.2 - admin [Thu, 30 Jul 2020 17:10:39 GMT] "POST /v1/account/change-password HTTP/1.0" - - "http://umbrel.local/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
manager | umbrel-manager
manager | Unable to change password
manager | /v1/account/change-password
manager | Error: Unable to change password
manager | at Object.changePassword (/usr/src/app/logic/auth.js:113:15)
manager | at async /usr/src/app/routes/v1/account.js:45:9
manager | at async /usr/src/app/utils/safeHandler.js:8:14
```

**Comment by mayankchhabra** [comment]
@qnjctckzz8 Can you quickly try `docker-compose logs -f middleware` while trying to change the password on the dashboard? Because `manager` makes a request to the `middleware` to change `lnd`'s password so that could be failing too.

**Comment by qnjctckzz8** [comment]
Middleware logs a bunch of stuff upon password change request but basically those two multiple times:

::ffff:10.11.0.2 - - [Sun, 02 Aug 2020 09:20:44 GMT] "GET /v1/lnd/lightning/payments HTTP/1.0" 500 60 "http://umbrel.local/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
middleware           | umbrel-middleware
middleware           | { LndError: Unable to change password
middleware           |     at rpcFn.call (/usr/src/app/services/lnd.js:68:18)
middleware           |     at Object.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:1210:9)
middleware           |     at InterceptingListener._callNext (/usr/src/app/node_modules/grpc/src/client_interceptors.js:568:42)
middleware           |     at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:618:8)
middleware           |     at callback (/usr/src/app/node_modules/grpc/src/client_interceptors.js:847:24)
middleware           |   name: 'LndError',
middleware           |   message: 'Unable to change password',
middleware           |   error:
middleware           |    { Error: 14 UNAVAILABLE: failed to connect to all addresses
middleware           |     at Object.exports.createStatusError (/usr/src/app/node_modules/grpc/src/common.js:91:15)
middleware           |     at Object.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:1209:28)
middleware           |     at InterceptingListener._callNext (/usr/src/app/node_modules/grpc/src/client_interceptors.js:568:42)
middleware           |     at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:618:8)
middleware           |     at callback (/usr/src/app/node_modules/grpc/src/client_interceptors.js:847:24)
middleware           |      code: 14,
middleware           |      metadata: Metadata { _internal_repr: {}, flags: 0 },
middleware           |      details: 'failed to connect to all addresses' },
middleware           |   statusCode: undefined }
middleware           | changePassword

middleware           | ::ffff:10.11.0.2 - - [Sun, 02 Aug 2020 09:21:04 GMT] "GET /v1/lnd/channel HTTP/1.0" 500 69 "http://umbrel.local/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"
middleware           | umbrel-middleware
middleware           | Unable to list invoices, failed to connect to all addresses
middleware           | /v1/lnd/lightning/invoices
middleware           | LndError: Unable to list invoices
middleware           |     at rpcFn.call (/usr/src/app/services/lnd.js:68:18)
middleware           |     at Object.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:1210:9)
middleware           |     at InterceptingListener._callNext (/usr/src/app/node_modules/grpc/src/client_interceptors.js:568:42)
middleware           |     at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:618:8)
middleware           |     at callback (/usr/src/app/node_modules/grpc/src/client_interceptors.js:847:24)

From what I understand that's the expected behavior while lnd is restarting.
Also I believe the request in the browser has already timed out at the point where I get these, that's how off the timing is.

**Comment by mayankchhabra** [comment]
Interesting, it looks like it's not a problem with `middleware` or `manager`, but `lnd`. 

Can you once again try changing password, this time with `docker-compose logs -f lnd`? Sorry to have you go through the pain over and over.

**Comment by qnjctckzz8** [comment]
I still don't think that there is a particular problem. I just think the timing is way off...

**Here are the logs (without peer info):**

lnd                  | 2020-08-03 20:58:42.578 [INF] LTND: Received terminated
lnd                  | 2020-08-03 20:58:42.579 [INF] LTND: Shutting down...
lnd                  | 2020-08-03 20:58:42.579 [INF] LTND: Gracefully shutting d                                                                                                                                                                                                                                                                                                                                                           own.
lnd                  | 2020-08-03 21:01:17.306 [INF] BTCN: Processed 1 block in                                                                                                                                                                                                                                                                                                                                                            the last 6m15.87s (height 642097, 2020-08-03 21:00:43 +0000 UTC)
lnd                  | 2020-08-03 21:01:17.742 [INF] BTCN: Attempting to fetch s                                                                                                                                                                                                                                                                                                                                                           et of un-checkpointed filters at height=642097, hash=00000000000000000003a82e0c4                                                                                                                                                                                                                                                                                                                                                           0e3a190fc2e35ab76cdfaa9731c33477d8de1
lnd                  | 2020-08-03 21:01:28.175 [INF] BTCN: Verified 1 filter hea                                                                                                                                                                                                                                                                                                                                                           der in the last 6m15.58s (height 642097, 2020-08-03 21:00:43 +0000 UTC)
lnd                  | 2020-08-03 21:01:28.714 [INF] BTCN: Lost peer 35.229.93.2                                                                                                                                                                                                                                                                                                                                                           13:8333 (outbound)
lnd                  | 2020-08-03 21:01:29.648 [INF] NTFN: New block: height=642                                                                                                                                                                                                                                                                                                                                                           097, sha=00000000000000000003a82e0c40e3a190fc2e35ab76cdfaa9731c33477d8de1
lnd                  | 2020-08-03 21:01:29.827 [INF] UTXN: Attempting to graduat                                                                                                                                                                                                                                                                                                                                                           e height=642097: num_kids=0, num_babies=0
lnd                  | 2020-08-03 21:03:32.011 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 028579be41e058d424606997103f7a866bdf0fe0df84a71088493fa901b3d8f6ae from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.140 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 026b742cea92cea6535f8688e5597bb874d8ddb6dab3500119a25cb25228d2a75e from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.211 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 021802799027508e8a8bf9a0ab96ea78a6a995926a0b1310561a74375a06e14de9 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.254 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 026c72dbf5019c10cc3a90448be1624fdc6021beb4fb689d4a91f0cdc3f7614d28 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.342 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 030fd8f3583144a1921cf9d5e1b5bcc51f3abcfe4ed7f4ec75ae6d5df13399c55d from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.422 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 0332eac72f489f38086e8653db6e8556a5848b56aff14ec4b6027e5665c6a4c4a2 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.499 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 022aa93f2a1180d008c6b40ec176903f48bde4e32e46db099719d2bb2857af029e from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.608 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 023ae2adb74a1defe29fc20edefe73e2f26242d60ee5419ae1024cf45c924bbb64 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.659 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 03dcc94ab317def2d988552e8d838d20cb5e86ba93c86098e43ba366fa843f5357 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.718 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 03344587d512b940bb96b4db40e4f915d1c402176b5c99913b0876413a81bf646e from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.805 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 03197c91a41e6db4d1776b1e85c3cd8ac7f0d8186b677e467a8cbd7c8b1c75bcde from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.881 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 02e29856dab8ddd9044c18486e4cab79ec717b490447af2d4831e290e48d58638a from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:32.925 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 024ed8913a7eb7f9c4f0f9b5de2cfe05414276b7d50b1e718fb6566147cd37918e from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:33.107 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 02c4cf316f63787dc9636249a02ce20ed166b467bb8ee81f0385fb5ae6c057ccc8 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:33.149 [INF] CHDB: Pruned unconnected no                                                                                                                                                                                                                                                                                                                                                           de 039199b7b5146fa2b0bd00a4c97ccbc4950c079ad5f9f982a8b8f2d8e00c828cd9 from chann                                                                                                                                                                                                                                                                                                                                                           el graph
lnd                  | 2020-08-03 21:03:33.150 [INF] CHDB: Pruned 15 unconnected                                                                                                                                                                                                                                                                                                                                                            nodes from the channel graph
lnd                  | 2020-08-03 21:03:34.115 [INF] CHFT: Adding 0 channels to                                                                                                                                                                                                                                                                                                                                                            event store
lnd                  | 2020-08-03 21:03:34.203 [INF] CHBU: Starting chanbackup.S                                                                                                                                                                                                                                                                                                                                                           ubSwapper
lnd                  | 2020-08-03 21:03:34.221 [INF] BTCN: Server listening on [                                                                                                                                                                                                                                                                                                                                                           ::]:9735
lnd                  | 2020-08-03 21:03:34.875 [INF] SRVR: Initializing peer net                                                                                                                                                                                                                                                                                                                                                           work bootstrappers!
lnd                  | 2020-08-03 21:03:34.969 [INF] SRVR: Creating DNS peer boo                                                                                                                                                                                                                                                                                                                                                           tstrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory]                                                                                                                                                                                                                                                                                                                                                            [lseed.bitcoinstats.com ]]
lnd                  | 2020-08-03 21:03:35.035 [INF] BTCN: Canceling block subsc                                                                                                                                                                                                                                                                                                                                                           ription: id=4
lnd                  | 2020-08-03 21:03:35.035 [INF] HSWC: HTLC Switch shutting                                                                                                                                                                                                                                                                                                                                                            down
lnd                  | 2020-08-03 21:03:35.035 [INF] HSWC: Block epoch canceled,                                                                                                                                                                                                                                                                                                                                                            decaying hash log shutting down
lnd                  | 2020-08-03 21:03:35.141 [INF] UTXN: UTXO nursery shutting                                                                                                                                                                                                                                                                                                                                                            down
lnd                  | 2020-08-03 21:03:35.142 [INF] BRAR: Breach arbiter shutti                                                                                                                                                                                                                                                                                                                                                           ng down
lnd                  | 2020-08-03 21:03:35.091 [INF] DISC: Attempting to bootstr                                                                                                                                                                                                                                                                                                                                                           ap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.dir                                                                                                                                                                                                                                                                                                                                                           ectory] [lseed.bitcoinstats.com ]]
lnd                  | 2020-08-03 21:03:35.218 [INF] DISC: Authenticated Gossipe                                                                                                                                                                                                                                                                                                                                                           r is stopping
lnd                  | 2020-08-03 21:03:35.280 [INF] CNCT: Stopping ChainArbitra                                                                                                                                                                                                                                                                                                                                                           tor
lnd                  | 2020-08-03 21:03:35.280 [INF] PRNF: Stopping PeerNotifier
lnd                  | 2020-08-03 21:03:35.544 [INF] CRTR: FilteredChainView sto                                                                                                                                                                                                                                                                                                                                                           pping
lnd                  | 2020-08-03 21:03:35.544 [INF] FNDG: Funding manager shutt                                                                                                                                                                                                                                                                                                                                                           ing down
lnd                  | 2020-08-03 21:03:35.545 [INF] CHBU: Stopping chanbackup.S                                                                                                                                                                                                                                                                                                                                                           ubSwapper
lnd                  | 2020-08-03 21:03:36.926 [INF] CHBU: Updating backup file                                                                                                                                                                                                                                                                                                                                                            at /data/.lnd/data/chain/bitcoin/mainnet/channel.backup
lnd                  | 2020-08-03 21:03:37.256 [INF] CHBU: Swapping old multi ba                                                                                                                                                                                                                                                                                                                                                           ckup file from /data/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.backup to /da                                                                                                                                                                                                                                                                                                                                                           ta/.lnd/data/chain/bitcoin/mainnet/channel.backup
lnd                  | 2020-08-03 21:03:37.257 [INF] CHFT: Stopping event store
lnd                  | 2020-08-03 21:03:37.893 [INF] DISC: Obtained 3 addrs to b                                                                                                                                                                                                                                                                                                                                                           ootstrap network with
lnd                  | 2020-08-03 21:03:37.921 [INF] RPCS: Stopping RPC Server
lnd                  | 2020-08-03 21:03:37.922 [INF] RPCS: Stopping RouterRPC Su                                                                                                                                                                                                                                                                                                                                                           b-RPC Server
lnd                  | 2020-08-03 21:03:37.922 [INF] RPCS: Stopping AutopilotRPC                                                                                                                                                                                                                                                                                                                                                            Sub-RPC Server
lnd                  | 2020-08-03 21:03:38.050 [INF] RPCS: Stopping ChainRPC Sub                                                                                                                                                                                                                                                                                                                                                           -RPC Server
lnd                  | 2020-08-03 21:03:38.050 [INF] RPCS: Stopping InvoicesRPC                                                                                                                                                                                                                                                                                                                                                            Sub-RPC Server
lnd                  | 2020-08-03 21:03:38.051 [INF] RPCS: Stopping WatchtowerCl                                                                                                                                                                                                                                                                                                                                                           ientRPC Sub-RPC Server
lnd                  | 2020-08-03 21:03:38.051 [INF] RPCS: Stopping SignRPC Sub-                                                                                                                                                                                                                                                                                                                                                           RPC Server
lnd                  | 2020-08-03 21:03:38.051 [INF] RPCS: Stopping VersionRPC S                                                                                                                                                                                                                                                                                                                                                           ub-RPC Server
lnd                  | 2020-08-03 21:03:38.051 [INF] RPCS: Stopping WalletKitRPC                                                                                                                                                                                                                                                                                                                                                            Sub-RPC Server
lnd                  | 2020-08-03 21:03:38.051 [INF] RPCS: Stopping WatchtowerRP                                                                                                                                                                                                                                                                                                                                                           C Sub-RPC Server
lnd                  | 2020-08-03 21:03:38.078 [INF] BTCN: Canceling block subsc                                                                                                                                                                                                                                                                                                                                                           ription: id=1
lnd                  | 2020-08-03 21:03:38.134 [INF] BTCN: Block manager shuttin                                                                                                                                                                                                                                                                                                                                                           g down
lnd                  | 2020-08-03 21:03:38.185 [INF] BTCN: Address manager shutt                                                                                                                                                                                                                                                                                                                                                           ing down
lnd                  | 2020-08-03 21:03:38.351 [INF] LTND: Shutdown complete
lnd                  | 2020-08-03 21:03:57.337 [INF] LTND: Version: 0.10.1-beta                                                                                                                                                                                                                                                                                                                                                            commit=v0.10.1-beta, build=production, logging=default
lnd                  | 2020-08-03 21:03:57.337 [INF] LTND: Active chain: Bitcoin                                                                                                                                                                                                                                                                                                                                                            (network=mainnet)
lnd                  | 2020-08-03 21:03:57.337 [INF] LTND: Opening the main data                                                                                                                                                                                                                                                                                                                                                           base, this might take a few minutes...
lnd                  | 2020-08-03 21:04:50.484 [INF] CHDB: Checking for schema u                                                                                                                                                                                                                                                                                                                                                           pdate: latest_version=13, db_version=13
lnd                  | 2020-08-03 21:04:50.485 [INF] LTND: Database now open (ti                                                                                                                                                                                                                                                                                                                                                           me_to_open=53.147112951s)!

**Comment by nolim1t** [comment]
I get the following when I try to bring down docker-compose.I assume things get restarted when  the password is changed.

The networking thing could be related. 

```
ERROR: error while removing network: network umbrel_net id cd4acce83dd3bbcf393b64cbf6636ecd5ff3c2d775036fedd9b76ada7763633e has active endpoints
```

**Comment by mayankchhabra** [comment]
Closing it since we dropped support for RPi 3. Thanks for your help, @qnjctckzz8!
