### ISSUE TITLE
Add in SSH key management API

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-manager#8]
For now the impact is quite low, but eventually we need to be able to secure access via ssh to authorized parties only, as the default password is exposed everywhere.

## What needs to happen

- Full write access to ```${HOME}/.ssh/authorized_keys``` by the manager to add and remove keys (1 line = 1 key)
- API to Read and write to this file
- Remove SSH password access from umbrel-os image (after this has done and tested)

**Comment by mayankchhabra** [comment]
Good concern regarding SSH access. We can look at doing it in a simple manner:

1. Ship Umbrel OS with default SSH password (as it is today).
2. When the user sets his password on `umbrel.local` on the first setup, update the SSH password to be the same password (so now it's the same password used by dashboard, lnd wallet, and SSH).
3. Whenever the user changes his password on `umbrel.local/settings`, update the SSH password to the new password as well.

This also makes it easy for the user to SSH into his node whenever he wants, using the same password without worrying about safely securing his private key.

**Comment by nolim1t** [comment]
I actually want to avoid passwords on SSH to begin with, and just use public keys.

The whole idea is that anyone whos able to use a SSH client and command line is also able to set up a public/private key pair.  Otherwise ssh will be not an option, and should be unavailable for their protection, while they use the frontend.

The default password is just a temporary measure.

**Comment by mayankchhabra** [comment]
As discussed, key-based SSH can never be much more secure than the security of the user's dashboard password when it comes to the "access to funds" (which is all that matters).

Hence to keep things simple, it makes much more sense to stick to the dashboard password being the SSH password as well.
