### ISSUE TITLE
API endpoint for retrieving and storing users currency preferences

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-manager#9]
To support customizable currencies (https://github.com/getumbrel/umbrel-dashboard/pull/103). backend support for  retrieving and storing users currency preferences so we can have the currency shown in their preference.

Default to USD ($)

Should have the:

* Currency Code
* Currency Symbol

Low priority though.

## Examples

![customizable-currencies](https://user-images.githubusercontent.com/83470/85278158-c0317f80-b4ae-11ea-86ac-6c647c159e82.png)

![yuan](https://user-images.githubusercontent.com/83470/85278280-f0791e00-b4ae-11ea-8175-dbfd7e5006d3.png)

**Comment by nolim1t** [comment]
Could add in something for storing preferences in https://github.com/getumbrel/umbrel-manager/blob/5ea3852dbe916137d9daaa83356f978891375127/logic/auth.js#L204

**Comment by mayankchhabra** [comment]
Let's do a new manager endpoint `POST /v1/account/preferences` that saves and updates preferences in `user.json`. 

Examples:

1. To change preferred currency
```
POST /v1/account/preferences
{
    "currency": "THB"
}
```

2. To switch between sats/btc
```
POST /v1/account/preferences

{
    "unit": "sats"
}
```

3. Update multiple preferences at one time:
```
POST /v1/account/preferences

{
    "currency": "THB"
    "unit": "sats"
}
```

Eg of updated `db/user.json`:

```
{
    name: "Satoshi"
    password: "hsvdy78d7fydfjdkfdf"
    seed: "shd789768239bcsd"
    unit: "sats"
    currency: "THB"
}

Later it'd be easy to implement more system settings, eg storing dark/light mode preference, etc.

Also `GET /v1/account/info` already returns user.json (except hashed password and encrypted seed) on the first load so we don't need to implement a separate way to retrieve user preferences in the dashboard.

**Comment by mayankchhabra** [comment]
And sure, we can save the default preferences on the registration like you said
https://github.com/getumbrel/umbrel-manager/blob/5ea3852dbe916137d9daaa83356f978891375127/logic/auth.js#L204

**Comment by mayankchhabra** [comment]
Plus we don't need to store the currency symbol on the backend. Just map the currency to its symbol on the front-end using https://gist.github.com/Fluidbyte/2973986

**Comment by nolim1t** [comment]
I added a fork for that currency symbol thing..

Added BTC and satoshis too, and fixed up the INR symbol

https://gist.github.com/nolim1t/4c2cf3bb68ca7aa1f85508c4ce006973

**Comment by nolim1t** [comment]
> Also `GET /v1/account/info` already returns user.json (except hashed password and encrypted seed) on the first load so we don't need to implement a separate way to retrieve user preferences in the dashboard.

Im down for using ```/v1/account/info``` first. Default to USD if its missing (and in the array). less is more ;-)

**Comment by mayankchhabra** [comment]
Always 💯

**Comment by nolim1t** [comment]
![error-handling](https://user-images.githubusercontent.com/83470/85301092-99387500-b4d1-11ea-8f68-20254daf66b0.png)

If rates don't exist

**Comment by nolim1t** [comment]
I've called the key ```stateCurrencyPreference``` (to accurately describe internally what it is) which can be added to user.json manually (if it doesn't exist it will default to USD).

**Comment by nolim1t** [comment]
We actually do need a new endpoint which just returns preferences only. Theres some weird issue which only lets an endpoint be requested once (maybe browser)

**Comment by mayankchhabra** [comment]
No worries, I'll take a deep look later after the public-beta task-list is finished off

**Comment by nolim1t** [comment]
sure this isn't important at all.. in fact I'd rather not even show government currencies ;)

**Comment by mayankchhabra** [comment]
Will create a master issue later
